freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script:
    - sudo pkg install -y sqlite3 
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm --installdeps --notest Alien::sqlite
    - sudo mv `which sqlite3` zort  #  trigger share build probe
  script:
    - perl Makefile.PL
    - sudo cpanm --installdeps .
    - make
    - make test
