freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script:
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm --installdeps Alien::sqlite
  script:
    - perl Makefile.PL
      make
      make test
